---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kafka-ui-configs
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/minikube/sync-code/kafka/kafka-ui/configs
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kafka-ui
  namespace: flux-system
spec:
  dependsOn:
    - name: kafka-ui-configs
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/third-parties/kafka-ui
  prune: true
  wait: true
  timeout: 5m0s