---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- calico-tigera.yaml
- calico.yaml
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: FELIX_IGNORELOOSERPF
        value: "true"
  target:
    kind: DaemonSet
    namespace: calico-system
    name: calico-node
