---
namespace: flux-system
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: FELIX_IGNORELOOSERPF
        value: "true"
  target:
    kind: DaemonSet
    namespace: calico-system
    name: calico-node
